# Generated by Django 5.2 on 2025-05-08 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=5, null=True, unique=True)),
                ('nisn', models.CharField(max_length=10, null=True, unique=True)),
                ('nama_lengkap', models.CharField(max_length=255, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=11, null=True)),
                ('tempat_lahir', models.CharField(max_length=255, null=True)),
                ('tanggal_lahir', models.DateField(null=True)),
                ('nama_orang_tua', models.CharField(max_length=255, null=True)),
                ('alamat', models.CharField(max_length=255, null=True)),
                ('no_hp_ortu', models.CharField(max_length=14, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('PPDB', 'PPDB'), ('Akademik', 'Akademik'), ('Libur', 'Libur'), ('Kegiatan', 'Kegiatan'), ('Keuangan', 'Keuangan'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('subjek', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('file_surat', models.FileField(blank=True, null=True, upload_to='akademik/surat_pengumuman/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minggu', models.CharField(max_length=50)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alfa', 'Alfa')], max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tkit.datasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=100)),
                ('wali_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datasiswa',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tkit.kelas'),
        ),
        migrations.CreateModel(
            name='OrangTuaMurid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_hp', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('siswa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ortu', to='tkit.datasiswa')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerkembanganSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Kognitif', 'Kognitif'), ('Motorik', 'Motorik'), ('Bahasa', 'Bahasa'), ('Sosial-Emosional', 'Sosial-Emosional'), ('Agama & Moral', 'Agama & Moral')], max_length=50)),
                ('deskripsi', models.TextField()),
                ('catatan', models.TextField()),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('guru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tkit.periode')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tkit.datasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuptk', models.CharField(max_length=16, null=True, unique=True)),
                ('tempat_lahir', models.CharField(max_length=255, null=True)),
                ('tanggal_lahir', models.DateField(null=True)),
                ('pendidikan_terakhir', models.CharField(choices=[('Tamat SD/Sederajat', 'Tamat SD/Sederajat'), ('SLTP/Sederajat', 'SLTP/Sederajat'), ('SLTA/Sederajat', 'SLTA/Sederajat'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=20, null=True)),
                ('nomor_hp', models.CharField(max_length=13, null=True, unique=True)),
                ('jabatan', models.CharField(choices=[('Guru', 'Guru'), ('Kepala Sekolah', 'Kepala Sekolah'), ('Staff', 'Staff'), ('Lainnya', 'Lainnya')], max_length=20, null=True)),
                ('tmt', models.DateField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
